services:
  db:
    image: postgres:16
    container_name: pas-db
    environment:
      POSTGRES_DB: pas
      POSTGRES_USER: pas
      POSTGRES_PASSWORD: pas
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pas"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod
    image: pas-backend:prod
    container_name: pas-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    image: pas-frontend:latest
#    container_name: pas-frontend
#    depends_on:
#      - backend
#    ports:
#      - "80:80"
#    environment:
#      - NGINX_PROXY_PASS=http://backend:8080