CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE ADDRESS(
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    STREET VARCHAR(60) NOT NULL,
    HOUSE_NUMBER VARCHAR(60) NOT NULL,
    PLZ INT NOT NULL,
    CITY VARCHAR(60) NOT NULL
);

CREATE TABLE USER_ENTITY
(
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID VARCHAR(20) NOT NULL UNIQUE,
    USER_TYPE VARCHAR(20) NOT NULL,
    ADDRESS_ID UUID NOT NULL,
    PHONE_NUMBER VARCHAR(16),
    EMAIL VARCHAR(50),
    HAS_CHILDREN BOOLEAN DEFAULT FALSE,
    HAS_GARDEN BOOLEAN DEFAULT FALSE,

    CONSTRAINT FK_ADDRESS
        FOREIGN KEY (ADDRESS_ID)
            REFERENCES ADDRESS(ID)
);

CREATE TABLE ADOPTION_REQUEST(
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ADOPTER_ID UUID NOT NULL,
    PET_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    REQUEST_STATUS VARCHAR(20) NOT NULL,

    CONSTRAINT FK_ADOPTER
        FOREIGN KEY (ADOPTER_ID)
            REFERENCES USER_ENTITY(ID)
    --CONSTRAINT FK_PET
      --  FOREIGN KEY (PET_ID)
        --    REFERENCES PET(ID)
);